SELECT DISTINCT PATIENTS.PATIENT_ID,
                CONCAT(PATIENTS.PATIENT_ID, LENGTH(LAST_NAME), YEAR(BIRTH_DATE)) AS TEMP_PASSWORD
FROM PATIENTS
INNER JOIN ADMISSIONS
ON ADMISSIONS.PATIENT_ID = PATIENTS.PATIENT_ID
