SELECT YEAR(ORDER_DATE) AS YEAR,
ROUND(SUM(QUANTITY*UNIT_PRICE*DISCOUNT), 2) AS MONEY_LOST
FROM ORDER_DETAILS
INNER JOIN ORDERS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
INNER JOIN PRODUCTS
ON PRODUCTS.PRODUCT_ID = ORDER_DETAILS.PRODUCT_ID
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEAR(ORDER_DATE) DESC
