SELECT PRODUCT_NAME,
       COMPANY_NAME,
       CATEGORY_NAME
FROM CATEGORIES
INNER JOIN PRODUCTS
ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID
INNER JOIN SUPPLIERS
ON SUPPLIERS.SUPPLIER_ID = PRODUCTS.SUPPLIER_ID
