SELECT CONCAT(FIRST_NAME, " ", LAST_NAME) AS FULL_NAME,
ROUND((HEIGHT/30.48), 1) AS HEIGHT,
ROUND(WEIGHT*2.205) AS WEIGHT,
BIRTH_DATE,
CASE
WHEN GENDER = "M" THEN "MALE"
ELSE "FEMALE"
END AS GENDER
FROM PATIENTS
