SELECT FIRST_NAME,
       LAST_NAME,
       ALLERGIES
FROM PATIENTS
WHERE ALLERGIES LIKE "PENICILLIN"
OR ALLERGIES LIKE "MORPHINE"
ORDER BY ALLERGIES ASC,
         FIRST_NAME ASC,
         LAST_NAME ASC
