SELECT PATIENT_ID,
       ATTENDING_DOCTOR_ID,
       DIAGNOSIS
FROM ADMISSIONS
WHERE (PATIENT_ID % 2 <> 0 AND ATTENDING_DOCTOR_ID IN (1, 5, 19))
OR (ATTENDING_DOCTOR_ID LIKE "%2%" AND LEN(PATIENT_ID) = 3)
