SELECT FIRST_NAME,
       LAST_NAME,
       BIRTH_DATE
FROM PATIENTS
WHERE YEAR(BIRTH_DATE) BETWEEN 1970 AND 1979
ORDER BY YEAR(BIRTH_DATE) ASC,
         MONTH(BIRTH_DATE) ASC,
         DAY(BIRTH_DATE) ASC
