SELECT CONCAT(PATIENTS.FIRST_NAME, " ", PATIENTS.LAST_NAME),
DIAGNOSIS,
CONCAT(DOCTORS.FIRST_NAME, " ", DOCTORS.LAST_NAME)
FROM PATIENTS
INNER JOIN ADMISSIONS
ON PATIENTS.PATIENT_ID = ADMISSIONS.PATIENT_ID
INNER JOIN DOCTORS
ON DOCTORS.DOCTOR_ID = ADMISSIONS.ATTENDING_DOCTOR_ID