SELECT CONCAT(PATIENTS.FIRST_NAME, " ", PATIENTS.LAST_NAME) AS FULL_NAME_PATIENT,
DIAGNOSIS,
CONCAT(DOCTORS.FIRST_NAME, " ", DOCTORS.LAST_NAME) AS FULL_NAME_DOCTOR
FROM PATIENTS
INNER JOIN ADMISSIONS
ON PATIENTS.PATIENT_ID = ADMISSIONS.PATIENT_ID
INNER JOIN DOCTORS
ON DOCTORS.DOCTOR_ID = ADMISSIONS.ATTENDING_DOCTOR_ID
