SELECT PATIENTS.PATIENT_ID,
PATIENTS.FIRST_NAME,
PATIENTS.LAST_NAME,
SPECIALTY
FROM PATIENTS
INNER JOIN ADMISSIONS
ON ADMISSIONS.PATIENT_ID = PATIENTS.PATIENT_ID
INNER JOIN DOCTORS
ON DOCTORS.DOCTOR_ID = ADMISSIONS.ATTENDING_DOCTOR_ID
WHERE DIAGNOSIS LIKE "EPILEPSY"
AND DOCTORS.FIRST_NAME LIKE "LISA"