SELECT CITY,
       COMPANY_NAME,
       CONTACT_NAME,
       "CUSTOMERS" AS RELATIONSHIP
FROM CUSTOMERS
UNION
SELECT CITY,
       COMPANY_NAME,
       CONTACT_NAME,
       "SUPPLIERS"
FROM SUPPLIERS
