SELECT DOCTOR_ID,
CONCAT(FIRST_NAME, " ", LAST_NAME) AS FULL_NAME,
MIN(ADMISSION_DATE),
MAX(ADMISSION_DATE)
FROM ADMISSIONS
INNER JOIN DOCTORS
ON ADMISSIONS.ATTENDING_DOCTOR_ID = DOCTORS.DOCTOR_ID
GROUP BY FULL_NAME