SELECT CASE
       WHEN PATIENT_ID % 2 = 0 THEN "YES"
       ELSE "NO"
       END AS HAS_INSURANCE,
       SUM(CASE
           WHEN PATIENT_ID % 2 = 0 THEN 10
           ELSE 50
           END) AS COST
FROM ADMISSIONS
GROUP BY HAS_INSURANCE
