WITH A AS
(SELECT
CASE
    WHEN PATIENT_ID % 2 = 0 THEN "YES"
    ELSE "NO"
    END AS HAS_INSURANCE,
CASE
    WHEN PATIENT_ID % 2 = 0 THEN 10
    ELSE 50
    END AS COST
FROM ADMISSIONS)

SELECT HAS_INSURANCE,
       SUM(COST) AS TOTAL_COST
FROM A GROUP BY HAS_INSURANCE
