SELECT *
FROM PATIENTS
WHERE FIRST_NAME LIKE "__R%"
AND GENDER LIKE "F"
AND (MONTH(BIRTH_DATE) IS 02
    OR MONTH(BIRTH_DATE) IS 05
    OR MONTH(BIRTH_DATE) IS 12)
AND (WEIGHT < 80 AND WEIGHT > 60)
AND PATIENT_ID % 2 <> 0
AND CITY LIKE "KINGSTON"
