SELECT FIRST_NAME,
       LAST_NAME,
       COUNT(*) AS NUM_ORDERS,
       CASE
       WHEN SHIPPED_DATE <= REQUIRED_DATE THEN "ON TIME"
       ELSE "LATE"
       END AS SHIPPED
FROM EMPLOYEES
INNER JOIN ORDERS
ON ORDERS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
GROUP BY FIRST_NAME, LAST_NAME, SHIPPED
ORDER BY LAST_NAME ASC,
	 FIRST_NAME ASC,
	 NUM_ORDERS DESC
